import 'package:flutter/material.dart';

class AppColors {
  static const Color gray = Color(0xFFA0A0A0);
  static const Color semiAccent = Color(0xFF7974E7);
  static const Color accentColor = Color(0xFF4A43EC);
  static const Color lightAccent = Color(0xFF7F88E5);
  static const Color activeAccent = Color(0xDC6E69F0);
  static const backgtoundLight = Color(0xFFFCFCFC);
  static const Color white2 = Color(0xFFFCFCFC);
  static const Color green800 = Color(0xFF166534);
  static const Color lightGreen = Color(0xFF29D697);
  static const Color green100 = Color(0xFFDCFCE7);
  static const Color purple950 = Color(0xFF3B0764);
  static const Color purple100 = Color(0xFFF3E8FF);
  static const Color blue800 = Color(0xFF1E40AF);
  static const Color blue100 = Color(0xFFDBEAFE);
  static const Color error = Color(0xFFDF4946);
  static const Color chartLine = Color(0xFFEAAB6E);
  static const Color belowChartLine = Color(0xFFF6E6D7);
  static const Color horizontalGridLine = Color(0xFFDFDFE3);
  static const Color orange = Color(0xFFF0635A);
  static const Color hover = Color(0xFFF3F1F6);
  static const Color darkGray = Color(0xFF828282);
  static const Color orange100 = Color(0xFFFBEAE2);
  static const Color purple = Color(0xFF9747FF);
  static const Color skyBlue = Color(0xFF7DD3FC);
  static const Color skyBlue300 = Color(0xFF93C5FD);
  static const Color lightPurple = Color(0xFFDAD9F9);
  static const Color orange950 = Color(0xFFF7931B);
  static const primaryLight = Color.fromARGB(255, 42, 35, 235);
  static const backgroundColorLight = Colors.white;
  static const secondaryLight = Color(0xFFDBDAFF);
  static const backgroundColorDark = Color(0xFF282C4A);
  static const bestForYouColor = Color(0xFFF0635A);
  static const developersColor = Color(0xFFF59762);
  static const newAddedColor = Color(0xFF29D697);
  static const bestInvestColor = Color(0xFF46CDFB);
  static const hotColor = Color(0xFFF0635A);
}
