class PropertyModel {
  late String name;
  late int price;
  late String location;
  late int area;
  late int beds;
  late int baths;
  late int kitchens;
  late String image;

  PropertyModel({
    required this.name,
    required this.price,
    required this.location,
    required this.area,
    required this.beds,
    required this.baths,
    required this.kitchens,
    required this.image,
  });
}

List<PropertyModel> data = [
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
  PropertyModel(
    name: "Deluxe Property",
    price: 2000,
    location: "2BW Street NY, New York",
    area: 2000,
    beds: 4,
    baths: 4,
    kitchens: 4,
    image: "assets/images/google.svg",
  ),
];
