import 'package:hessa/features/wallet/data/models/transaction_model.dart';

final List<TransactionModel> transactions = [
  TransactionModel(
    type: "Pay Shares",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 1250.50,
    category: "Expense",
    propertyName: "Skyline Tower",
  ),
  TransactionModel(
    type: "Pay Shares",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 1250.50,
    category: "Expense",
    propertyName: "Skyline Tower",
  ),
  TransactionModel(
    type: "Fees",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 175740.50,
    category: "Expense",
    propertyName: "Tower",
  ),
  TransactionModel(
    type: "Pay Shares",
    date: "08-May-2024",
    currency: "EGP",
    amount: 400,
    category: "Expense",
    propertyName: "Riverfront Plaza",
  ),
  TransactionModel(
    type: "Pay Shares",
    date: "04-Aug-2023",
    currency: "EGP",
    amount: 200,
    category: "Expense",
    propertyName: "Downtown Lofts",
  ),
  TransactionModel(
    type: "Rent",
    date: "01-Jan-2024",
    currency: "EGP",
    amount: 500,
    category: "Income",
  ),
  TransactionModel(
    type: "Bonus",
    date: "15-Mar-2024",
    currency: "EGP",
    amount: 300,
    category: "Income",
  ),
  TransactionModel(
    type: "Pay Shares",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 1250.50,
    category: "Expense",
    propertyName: "Skyline Tower",
  ),
  TransactionModel(
    type: "Fees",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 1250.50,
    category: "Expense",
    propertyName: "Skyline Tower",
  ),
  TransactionModel(
    type: "Pay Shares",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 175740.50,
    category: "Expense",
    propertyName: "Tower",
  ),
  TransactionModel(
    type: "Fees",
    date: "08-May-2024",
    currency: "EGP",
    amount: 400,
    category: "Expense",
    propertyName: "Riverfront Plaza",
  ),
  TransactionModel(
    type: "Fees",
    date: "04-Aug-2023",
    currency: "EGP",
    amount: 200,
    category: "Expense",
    propertyName: "Downtown Lofts",
  ),
  TransactionModel(
    type: "Rent",
    date: "01-Jan-2024",
    currency: "EGP",
    amount: 500,
    category: "Income",
  ),
  TransactionModel(
    type: "Bonus",
    date: "15-Mar-2024",
    currency: "EGP",
    amount: 300,
    category: "Income",
  ),
  TransactionModel(
    type: "Withdrawl",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 1250.50,
    category: "Expense",
    propertyName: "Skyline Tower",
  ),
  TransactionModel(
    type: "Deposit",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 1250.50,
    category: "Income",
    propertyName: "Skyline Tower",
  ),
  TransactionModel(
    type: "Withdrawal",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 175740.50,
    category: "Expense",
    propertyName: "Tower",
  ),
  TransactionModel(
    type: "Deposit",
    date: "08-May-2024",
    currency: "EGP",
    amount: 400,
    category: "Income",
    propertyName: "Riverfront Plaza",
  ),
  TransactionModel(
    type: "Deposit",
    date: "04-Aug-2023",
    currency: "EGP",
    amount: 200,
    category: "Income",
    propertyName: "Downtown Lofts",
  ),
  TransactionModel(
    type: "Rent",
    date: "01-Jan-2024",
    currency: "EGP",
    amount: 500,
    category: "Income",
  ),
  TransactionModel(
    type: "Bonus",
    date: "15-Mar-2024",
    currency: "EGP",
    amount: 300,
    category: "Income",
  ),
  TransactionModel(
    type: "Withdrawal",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 1250.50,
    category: "Expense",
    propertyName: "Skyline Tower",
  ),
  TransactionModel(
    type: "Deposit",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 1250.50,
    category: "Income",
    propertyName: "Skyline Tower",
  ),
  TransactionModel(
    type: "Pay Shares",
    date: "04-Jan-2024",
    currency: "EGP",
    amount: 175740.50,
    category: "Expense",
    propertyName: "Tower",
  ),
  TransactionModel(
    type: "Fees",
    date: "08-May-2024",
    currency: "EGP",
    amount: 400,
    category: "Expense",
    propertyName: "Riverfront Plaza",
  ),
  TransactionModel(
    type: "Fees",
    date: "04-Aug-2023",
    currency: "EGP",
    amount: 200,
    category: "Expense",
    propertyName: "Downtown Lofts",
  ),
  TransactionModel(
    type: "Rent",
    date: "01-Jan-2024",
    currency: "EGP",
    amount: 500,
    category: "Income",
  ),
  TransactionModel(
    type: "Bonus",
    date: "15-Mar-2024",
    currency: "EGP",
    amount: 300,
    category: "Income",
  ),
];
