// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnCBjvle-LW9lFbkjJAq2EmJnJRjzeBFk',
    appId: '1:420569284844:web:bee84a41fc5289686365c9',
    messagingSenderId: '420569284844',
    projectId: 'hessah-f080a',
    authDomain: 'hessah-f080a.firebaseapp.com',
    storageBucket: 'hessah-f080a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA90GIfXuCRdJiquqf4ijYBW6UAuPKQcAo',
    appId: '1:420569284844:android:cdab38b3d94781916365c9',
    messagingSenderId: '420569284844',
    projectId: 'hessah-f080a',
    storageBucket: 'hessah-f080a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe1ecFg27GqJI092z3USwYh_UJrHcYzNE',
    appId: '1:420569284844:ios:62b557b8f419cdf76365c9',
    messagingSenderId: '420569284844',
    projectId: 'hessah-f080a',
    storageBucket: 'hessah-f080a.firebasestorage.app',
    iosClientId: '420569284844-oeubde09oi44frtka1gbsujjvd7ds1l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hessa',
  );
}
