name: 7essa CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter Version 3.29.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: 7essa-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Install Flutter 3.29.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          architecture: x64

      - name: Install Dependencies
        run: flutter pub get

      - name: Create/Modify Podfile with iOS 13.0 Support
        run: |
          cd ios
          
          # Create Podfile if it doesn't exist
          flutter build ios --release --no-codesign || true
          
          # Force platform iOS 13.0
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios.*/platform :ios, '13.0'/" Podfile
          else
            echo "platform :ios, '13.0'" | cat - Podfile > temp && mv temp Podfile
          fi
          
          # Add post_install block if missing
          if ! grep -q "post_install do" Podfile; then
            cat << 'EOF' >> Podfile

          post_install do |installer|
          installer.pods_project.targets.each do |target|
          flutter_additional_ios_build_settings(target)
          target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
          end
          end
          EOF
          fi
          
          echo "✅ Final Podfile:"
          cat Podfile

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: |
          cd ios
          pod install --verbose

      - name: Build iOS IPA
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r app.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: 7essa-ipa
          path: build/ios/iphoneos/app.ipa
