name: 7essa CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter 3.29.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Auto-increment version in pubspec.yaml
        id: versioning
        run: |
          current_version=$(grep '^version:' pubspec.yaml | awk '{print $2}')

          if [[ "$current_version" == *"+"* ]]; then
            base_version="${current_version%%+*}"
            build_number="${current_version##*+}"
          else
            base_version="$current_version"
            build_number=0
          fi

          new_build_number=$((build_number + 1))
          new_version="${base_version}+${new_build_number}"

          sed -i "s/^version:.*/version: $new_version/" pubspec.yaml

          echo "New version: $new_version"
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hessah
          path: build/app/outputs/flutter-apk/app-release.apk
