name: 7essa CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter Version 3.29.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache

      - name: Get and Upgrade Dependencies
        run: |
          flutter pub get
          flutter pub upgrade

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: 7essa-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Install Flutter Version 3.29.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          architecture: x64

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache

      - name: Get and Upgrade Dependencies
        run: |
          flutter pub get
          flutter pub upgrade

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Update Podfile
        run: |
          if grep -q "platform :ios" ios/Podfile; then
            sed -i '' "s/platform :ios.*/platform :ios, '13.0'/" ios/Podfile
          else
            echo "platform :ios, '13.0'" >> ios/Podfile
          fi
          if ! grep -q "post_install" ios/Podfile; then
            cat << 'EOF' >> ios/Podfile
          post_install do |installer|
          installer.pods_project.targets.each do |target|
          flutter_additional_ios_build_settings(target)
          target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
          end
          end
          EOF
          fi
          cat ios/Podfile


      - name: Build iOS IPA (no code signing)
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r app.ipa Payload

      - name: List IPA Directory Contents
        run: ls -la build/ios/iphoneos

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: 7essa-ipa
          path: build/ios/iphoneos/app.ipa
